name: conda-env
channels:
  - conda-forge
dependencies:
  - pip
  - jupyterlab
  - jupyterlab_vim
  - llm
  - sqlite
  - sqlite-utils
  - pip:
      - sqlite-vec
variables:
  ENVIRONMENT_LOADED: roombot
